# Game config
FRAME_RATE = 60
WORLD_WIDTH = 800
WORLD_HEIGHT = 600
BACKGROUND_COLOR = (100, 149, 237)

# Colors
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
MAGENTA = (255, 0, 255)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# Dog data
DOG_START_X = WORLD_WIDTH / 2
DOG_START_Y = WORLD_HEIGHT / 2
DOG_MOVE_SPEED = 5.5
DOG_COLOR = YELLOW
DOG_WIDTH = 16
DOG_HEIGHT = 32

# Sheep data
SHEEP_ATTACK_RANGE = 200
SHEEP_START_X = 100
SHEEP_START_Y = 100
SHEEP_MOVE_SPEED = 5
SHEEP_COLOR = GREEN
SHEEP_HUNTER_COLOR = MAGENTA
SHEEP_WIDTH = 16
SHEEP_HEIGHT = 32
SHEEP_COLLIDE_TIMEOUT = 120
SHEEP_FLASH_TIMEOUT = 5

# UI Toggles
SHEEP_VELOCITY_LINES = True
DOG_FORCE_LINES = True
BOUNDARY_FORCE_LINES = True
NEIGHBOR_LINES = True
BOUNDING_BOXES = True

# Force Toggles
DOG_FORCES = True
ALIGNMENT_FORCES = True
SEPARATION_FORCES = True
COHESION_FORCES = True
BOUNDARY_FORCES = True