# Game config
FRAME_RATE = 60
WORLD_WIDTH = 800
WORLD_HEIGHT = 600
BACKGROUND_COLOR = (100, 149, 237)

# Colors
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
BLUE = (0, 0, 255)
GREEN = (0, 255, 0)
MAGENTA = (255, 0, 255)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# Dog data
DOG_START_X = WORLD_WIDTH / 2
DOG_START_Y = WORLD_HEIGHT / 2
DOG_MOVE_SPEED = 5.5
DOG_WIDTH = 16
DOG_HEIGHT = 32

# Sheep data
SHEEP_ATTACK_RANGE = 200
SHEEP_START_X = 100
SHEEP_START_Y = 100
SHEEP_MOVE_SPEED = 1
SHEEP_WIDTH = 16
SHEEP_HEIGHT = 32
SHEEP_NEIGHBOR_RADIUS = 200
SHEEP_BOUNDARY_RADIUS = 50

# UI Toggles
VELOCITY_LINES = True
BOUNDING_BOXES = True
DOG_FORCE_LINES = True
BOUNDARY_FORCE_LINES = True
NEIGHBOR_FORCE_LINES = True

# Force Toggles
DOG_FORCES = False
ALIGNMENT_FORCES = False
SEPARATION_FORCES = False
COHESION_FORCES = False
BOUNDARY_FORCES = False

# Force Weights
DEFAULT_DOG_WEIGHT = 0.2
DEFAULT_ALIGNMENT_WEIGHT = 0.3
DEFAULT_SEPARATION_WEIGHT = 0.325
DEFAULT_COHESION_WEIGHT = 0.3
DEFAULT_BOUNDARY_WEIGHT = 0.2

CURRENT_DOG_WEIGHT = 0
CURRENT_ALIGNMENT_WEIGHT = 0
CURRENT_SEPARATION_WEIGHT = 0
CURRENT_COHESION_WEIGHT = 0
CURRENT_BOUNDARY_WEIGHT = 0